# ansible/host_vars/access04.yml
hostname: access04
loopback: 10.0.255.104

interfaces:
  # Uplink to dist02 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.19/31
    peer_ip: 10.0.2.18
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access04
  - name: eth6
    ip: 10.0.6.1/24

bfd_peers:
  - { ip: 10.0.2.18, iface: eth5 }
