# ansible/host_vars/access03.yml
hostname: access03
loopback: 10.0.255.103

interfaces:
  # Uplink to dist01 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.17/31
    peer_ip: 10.0.2.16
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access03
  - name: eth6
    ip: 10.0.5.1/24

bfd_peers:
  - { ip: 10.0.2.16, iface: eth5 }
