# ansible/host_vars/access12.yml
hostname: access12
loopback: 10.0.255.112

interfaces:
  # Uplink to dist04 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.35/31
    peer_ip: 10.0.2.34
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access12
  - name: eth6
    ip: 10.0.14.1/24

bfd_peers:
  - { ip: 10.0.2.34, iface: eth5 }
