# ansible/host_vars/access06.yml
hostname: access06
loopback: 10.0.255.106

interfaces:
  # Uplink to dist02 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.23/31
    peer_ip: 10.0.2.22
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access06
  - name: eth6
    ip: 10.0.8.1/24

bfd_peers:
  - { ip: 10.0.2.22, iface: eth5 }
