# ansible/host_vars/access01.yml
hostname: access01
loopback: 10.0.255.101

interfaces:
  # Uplink to dist01 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.13/31
    peer_ip: 10.0.2.12
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access01
  - name: eth6
    ip: 10.0.3.1/24

bfd_peers:
  - { ip: 10.0.2.12, iface: eth5 }
