# ansible/host_vars/access05.yml
hostname: access05
loopback: 10.0.255.105

interfaces:
  # Uplink to dist02 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.21/31
    peer_ip: 10.0.2.20
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access05
  - name: eth6
    ip: 10.0.7.1/24

bfd_peers:
  - { ip: 10.0.2.20, iface: eth5 }
