# ansible/host_vars/access11.yml
hostname: access11
loopback: 10.0.255.111

interfaces:
  # Uplink to dist04 (P2P /31, Area 1)
  - name: eth5
    ip: 10.0.2.33/31
    peer_ip: 10.0.2.32
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # LAN for clients behind access11
  - name: eth6
    ip: 10.0.13.1/24

bfd_peers:
  - { ip: 10.0.2.32, iface: eth5 }
