# ansible/host_vars/dist01.yml
hostname: dist01
loopback: 10.0.255.11

interfaces:
  # Uplink to Core (Area 0)
  - name: eth5
    ip: 10.0.1.9/31
    peer_ip: 10.0.1.8
    area: 0
    key: SuperSecret123Area0
    ospf_type: point-to-point

  # Dist full-mesh (Area 1)
  - name: eth1   # to dist02 eth1
    ip: 10.0.2.0/31
    peer_ip: 10.0.2.1
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  - name: eth2   # to dist03 eth1
    ip: 10.0.2.2/31
    peer_ip: 10.0.2.3
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  - name: eth3   # to dist04 eth1
    ip: 10.0.2.4/31
    peer_ip: 10.0.2.5
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  # Downlinks to Access (Area 1)
  - name: eth4   # to access01 eth5
    ip: 10.0.2.12/31
    peer_ip: 10.0.2.13
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  - name: eth6   # to access02 eth5
    ip: 10.0.2.14/31
    peer_ip: 10.0.2.15
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point

  - name: eth7   # to access03 eth5
    ip: 10.0.2.16/31
    peer_ip: 10.0.2.17
    area: 1
    key: SuperSecret123Area1
    ospf_type: point-to-point
